# General Settings
title = "Mountain - Coming Soon & Under Construction Hugo Theme"
baseURL = "" #YOUR SITE URL
languageCode = "en-us"
theme = "mountain"
resourceDir = "resources"
[pagination]
  pagerSize = 4
summaryLength = 50
DefaultContentLanguage = "en" # Site language. Available translations in the theme's `/i18n` directory.


# Menu Settings
[menu]
[[menu.main]]
  identifier = "slideshow"
  name = "Data Visualizations"
  url = ""
  weight = 1
  [[menu.main]]
    identifier = "constellation-slideshow-images"
    parent = "slideshow"
    name = "Constellation"
    url = "/slideshow-images/constellation/"
    weight = 5
  [[menu.main]]
    identifier = "geometric-slideshow-images"
    parent = "slideshow"
    name = "Geometric"
    url = "/slideshow-images/geometric/"
    weight = 7
  [[menu.main]]
    identifier = "low-poly-slideshow-images"
    parent = "slideshow"
    name = "Low poly"
    url = "/slideshow-images/low-poly/"
    weight = 8
  [[menu.main]]
    identifier = "particles-slideshow-images"
    parent = "slideshow"
    name = "Particles"
    url = "/slideshow-images/particles/"
    weight = 9
  [[menu.main]]
    identifier = "winter-slideshow-images"
    parent = "slideshow"
    name = "Winter"
    url = "/slideshow-images/winter/"
    weight = 12
[[menu.main]]
  identifier = "pack-1"
  name = "Swarm Pack"
  url = ""
  weight = 4
  [[menu.main]]
    identifier = "alien-pack-1"
    parent = "pack-1"
    name = "Alien"
    url = "/pack-1/alien/"
    weight = 2
  [[menu.main]]
    identifier = "aurora-pack-1"
    parent = "pack-1"
    name = "Aurora"
    url = "/pack-1/aurora/"
    weight = 3
  [[menu.main]]
    identifier = "coalesce-pack-1"
    parent = "pack-1"
    name = "Coalesce"
    url = "/pack-1/coalesce/"
    weight = 4
  [[menu.main]]
    identifier = "connections-pack-1"
    parent = "pack-1"
    name = "Connections"
    url = "/pack-1/connections/"
    weight = 5
  [[menu.main]]
    identifier = "gravity-pack-1"
    parent = "pack-1"
    name = "Gravity"
    url = "/pack-1/gravity/"
    weight = 6
  [[menu.main]]
    identifier = "html5-video-pack-1"
    parent = "pack-1"
    name = "HTML5 Video"
    url = "/pack-1/html5-video/"
    weight = 7
  [[menu.main]]
    identifier = "liquid-pack-1"
    parent = "pack-1"
    name = "Liquid"
    url = "/pack-1/liquid/"
    weight = 8
  [[menu.main]]
    identifier = "magneto-pack-1"
    parent = "pack-1"
    name = "Magneto"
    url = "/pack-1/magneto/"
    weight = 9
  [[menu.main]]
    identifier = "mosaic-pack-1"
    parent = "pack-1"
    name = "Mosaic"
    url = "/pack-1/mosaic/"
    weight = 10
  [[menu.main]]
    identifier = "orbit-pack-1"
    parent = "pack-1"
    name = "Orbit"
    url = "/pack-1/orbit/"
    weight = 11
  [[menu.main]]
    identifier = "pipeline-pack-1"
    parent = "pack-1"
    name = "Pipeline"
    url = "/pack-1/pipeline/"
    weight = 12
  [[menu.main]]
    identifier = "rain-video-pack-1"
    parent = "pack-1"
    name = "Rain Video"
    url = "/pack-1/rain-video/"
    weight = 13
  [[menu.main]]
    identifier = "shift-pack-1"
    parent = "pack-1"
    name = "Shift"
    url = "/pack-1/shift/"
    weight = 14
  [[menu.main]]
    identifier = "stardust-pack-1"
    parent = "pack-1"
    name = "Stardust"
    url = "/pack-1/stardust/"
    weight = 15
  [[menu.main]]
    identifier = "starfield-pack-1"
    parent = "pack-1"
    name = "Starfield"
    url = "/pack-1/starfield/"
    weight = 16
  [[menu.main]]
    identifier = "surface-pack-1"
    parent = "pack-1"
    name = "Surface"
    url = "/pack-1/surface/"
    weight = 17
  [[menu.main]]
    identifier = "swirl-pack-1"
    parent = "pack-1"
    name = "Swirl"
    url = "/pack-1/swirl/"
    weight = 18
  [[menu.main]]
    identifier = "dots-pack-1"
    parent = "pack-1"
    name = "Dots"
    url = "/pack-1/dots/"
    weight = 19
  [[menu.main]]
    identifier = "heuristics-pack-1"
    parent = "pack-1"
    name = "Heuristics"
    url = "/pack-1/heuristics/"
    weight = 20
[[menu.main]]
  identifier = "pack-2"
  name = "Pack #2"
  url = ""
  weight = 5
  [[menu.main]]
    identifier = "birds-pack-2"
    parent = "pack-2"
    name = "Birds"
    url = "/pack-2/birds/"
    weight = 1
  [[menu.main]]
    identifier = "boreal-sky-pack-2"
    parent = "pack-2"
    name = "Boreal Sky"
    url = "/pack-2/boreal-sky/"
    weight = 2
  [[menu.main]]
    identifier = "brick-tunnel-pack-2"
    parent = "pack-2"
    name = "Brick Tunnel"
    url = "/pack-2/brick-tunnel/"
    weight = 3
  [[menu.main]]
    identifier = "clouds-pack-2"
    parent = "pack-2"
    name = "Clouds"
    url = "/pack-2/clouds/"
    weight = 4
  [[menu.main]]
    identifier = "colors-pack-2"
    parent = "pack-2"
    name = "Colors"
    url = "/pack-2/colors/"
    weight = 5
  [[menu.main]]
    identifier = "confetti-lines-pack-2"
    parent = "pack-2"
    name = "Confetti Lines"
    url = "/pack-2/confetti-lines/"
    weight = 6
  [[menu.main]]
    identifier = "coronavirus-pack-2"
    parent = "pack-2"
    name = "Coronavirus"
    url = "/pack-2/coronavirus/"
    weight = 7
  [[menu.main]]
    identifier = "glitch-pack-2"
    parent = "pack-2"
    name = "Glitch"
    url = "/pack-2/glitch/"
    weight = 8
  [[menu.main]]
    identifier = "globe-pack-2"
    parent = "pack-2"
    name = "Globe"
    url = "/pack-2/globe/"
    weight = 9
  [[menu.main]]
    identifier = "hawking-pack-2"
    parent = "pack-2"
    name = "Hawking"
    url = "/pack-2/hawking/"
    weight = 10
  [[menu.main]]
    identifier = "hills-pack-2"
    parent = "pack-2"
    name = "Hills"
    url = "/pack-2/hills/"
    weight = 11
  [[menu.main]]
    identifier = "landscape-1-pack-2"
    parent = "pack-2"
    name = "Landscape 1"
    url = "/pack-2/landscape"
    weight = 12
  [[menu.main]]
    identifier = "landscape-2-pack-2"
    parent = "pack-2"
    name = "Landscape 2"
    url = "/pack-2/landscape-2/"
    weight = 13
  [[menu.main]]
    identifier = "net-pack-2"
    parent = "pack-2"
    name = "Net"
    url = "/pack-2/net/"
    weight = 14
  [[menu.main]]
    identifier = "physics-pack-2"
    parent = "pack-2"
    name = "Physics"
    url = "/pack-2/physics/"
    weight = 15
  [[menu.main]]
    identifier = "quantum-pack-2"
    parent = "pack-2"
    name = "Quantum"
    url = "/pack-2/quantum/"
    weight = 16
  [[menu.main]]
    identifier = "star-wars-pack-2"
    parent = "pack-1"
    name = "Star Wars"
    url = "/pack-2/star-wars/"
    weight = 17
  [[menu.main]]
    identifier = "stars-lines-pack-2"
    parent = "pack-2"
    name = "Stars Lines"
    url = "/pack-2/stars-lines/"
    weight = 18
  [[menu.main]]
    identifier = "topology-pack-2"
    parent = "pack-2"
    name = "Topology"
    url = "/pack-2/topology/"
    weight = 19
  [[menu.main]]
    identifier = "triangle-pack-2"
    parent = "pack-2"
    name = "Triangle"
    url = "/pack-2/triangle/"
    weight = 20
  [[menu.main]]
    identifier = "water-droplet-pack-2"
    parent = "pack-2"
    name = "Water Droplet"
    url = "/pack-2/water-droplet/"
    weight = 21
[[menu.main]]
  identifier = "blog"
  name = "Blog"
  url = "blog/"
  weight = 6

# Main Settings
[params]
defaultLogo = "Mountain"
defaultKeywords = ["geospatial data science", "machine learning", "gps", "movement pattern", "trajectory profiling", "GPS telemetry", "offroad", "remote", "connectivity", "starlink", "onboard sensors", "vehicle technology"]
defaultDescription = "Data from the Field - geospatial data science, machine learning engineering from the field, usually off-road"
dateFormat = "January 2, 2006"
authorName = "jcachat"
disqusComments = "mountain-hugo" #YOUR DISQUS COMMENTS SHORTNAME
googleAnalytics = "" #YOUR GOOGLE ANALYTICS CODE

# Preloader Settings
[params.preloader]
logo = "images/spinner.gif"

# Sidebar
[params.sidebar]
enable = 1 #SIDEBAR SHOW: [ 1 - yes, 0 - no ]
search = 1 #SIDEBAR SEARCH WIDGET: [ 1 - yes, 0 - no ]
latestPosts = 1 #SIDEBAR LATEST POSTS WIDGET: [ 1 - yes, 0 - no ]
categories = 1 #SIDEBAR CATEGORIES TAXONOMY WIDGET: [ 1 - yes, 0 - no ]
tags = 1 #SIDEBAR TAG TAXONOMY WIDGET: [ 1 - yes, 0 - no ]

# Footer Settings
[params.footer]
copyright = "Data from the Field © 2025. Design & Coded by <a href='https://jcachat.com' target='_blank'> Jonathan Cachat / CCV Research, LLC.</a>"

# Up Button Settings
[params.upBtn]
icon = "fa-solid fa-chevron-up"
url = "#top"

# Social Settings
[[params.social]]
title = "YouTube"
icon = "fa-brands fa-youtube"
url = "https://www.youtube.com/@jcachat"
[[params.social]]
title = "Twitter"
icon = "fa-brands fa-x-twitter"
url = "https://www.x.com/jcachat"
[[params.social]]
title = "LinkedIn"
icon = "fa-brands fa-linkedin"
url = "https://linkedin.com/in/jcachat"
[[params.social]]
title = "Instagram"
icon = "fa-brands fa-instagram"
url = "https://www.instagram.com/jcachat"


# Sitemap Settings
[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[outputs]
home = ["HTML", "RSS", "JSON"]