# General Settings
title = "Data From The Field - geospatial data science, machine learning engineering from the field, usually off-road"
baseURL = "datafromthefield.com" #YOUR SITE URL
languageCode = "en-us"
theme = "mountain"
resourceDir = "resources"
[pagination]
  pagerSize = 4
summaryLength = 50
DefaultContentLanguage = "en" # Site language. Available translations in the theme's `/i18n` directory.


# Menu Settings
[menu]
[[menu.main]]
  identifier = "About"
  name = "About"
  url = ""
  weight = 1
[[menu.main]]
  identifier = "swarm-pack"
  name = "Swarm Pack"
  url = ""
  weight = 2
  [[menu.main]]
    identifier = "geometric-slideshow-images"
    parent = "swarm-pack"
    name = "Geometric"
    url = "/swarm-pack/geometric/"
    weight = 1
  [[menu.main]]
    identifier = "alien-swarm-pack"
    parent = "swarm-pack"
    name = "Alien"
    url = "/swarm-pack/alien/"
    weight = 2
  [[menu.main]]
    identifier = "birds-swarm-pack"
    parent = "swarm-pack"
    name = "Birds"
    url = "/swarm-pack/birds/"
    weight = 3
  [[menu.main]]
    identifier = "coalesce-swarm-pack"
    parent = "swarm-pack"
    name = "Coalesce"
    url = "/swarm-pack/coalesce/"
    weight = 4
  [[menu.main]]
    identifier = "connections-swarm-pack"
    parent = "swarm-pack"
    name = "Connections"
    url = "/swarm-pack/connections/"
    weight = 5
  [[menu.main]]
    identifier = "constellation-swarm-pack"
    parent = "swarm-pack"
    name = "Constellation"
    url = "/swarm-pack/constellation/"
    weight = 5
  [[menu.main]]
    identifier = "dots-swarm-pack"
    parent = "swarm-pack"
    name = "Dots"
    url = "/swarm-pack/dots/"
    weight = 6
  [[menu.main]]
    identifier = "gravity-swarm-pack"
    parent = "swarm-pack"
    name = "Gravity"
    url = "/swarm-pack/gravity/"
    weight = 7
  [[menu.main]]
    identifier = "particles-swarm-pack"
    parent = "swarm-pack"
    name = "Particles"
    url = "/swarm-pack/particles/"
    weight = 8
  [[menu.main]]
    identifier = "magneto-swarm-pack"
    parent = "swarm-pack"
    name = "Magneto"
    url = "/swarm-pack/magneto/"
    weight = 9
  [[menu.main]]
    identifier = "mosaic-swarm-pack"
    parent = "swarm-pack"
    name = "Mosaic"
    url = "/swarm-pack/mosaic/"
    weight = 10
  [[menu.main]]
    identifier = "orbit-swarm-pack"
    parent = "swarm-pack"
    name = "Orbit"
    url = "/swarm-pack/orbit/"
    weight = 11
  [[menu.main]]
    identifier = "pipeline-swarm-pack"
    parent = "swarm-pack"
    name = "Pipeline"
    url = "/swarm-pack/pipeline/"
    weight = 12
  [[menu.main]]
    identifier = "low-poly-swarm-pack"
    parent = "swarm-pack"
    name = "Low poly"
    url = "/swarm-pack/low-poly/"
    weight = 13
  [[menu.main]]
    identifier = "shift-swarm-pack"
    parent = "swarm-pack"
    name = "Shift"
    url = "/swarm-pack/shift/"
    weight = 14
  [[menu.main]]
    identifier = "stardust-swarm-pack"
    parent = "swarm-pack"
    name = "Stardust"
    url = "/swarm-pack/stardust/"
    weight = 15
  [[menu.main]]
    identifier = "hawking-swarm-pack"
    parent = "swarm-pack"
    name = "Hawking"
    url = "/swarm-pack/hawking/"
    weight = 16
  [[menu.main]]
    identifier = "swirl-swarm-pack"
    parent = "swarm-pack"
    name = "Swirl"
    url = "/swarm-pack/swirl/"
    weight = 17
  [[menu.main]]
    identifier = "globe-swarm-pack"
    parent = "swarm-pack"
    name = "Globe"
    url = "/swarm-pack/globe/"
    weight = 18
  [[menu.main]]
    identifier = "heuristics-swarm-pack"
    parent = "swarm-pack"
    name = "Heuristics"
    url = "/swarm-pack/heuristics/"
    weight = 19
    [[menu.main]]
    identifier = "net-swarm-pack"
    parent = "swarm-pack"
    name = "Net"
    url = "/swarm-pack/net/"
    weight = 20
  [[menu.main]]
    identifier = "physics-swarm-pack"
    parent = "swarm-pack"
    name = "Physics"
    url = "/swarm-pack/physics/"
    weight = 21
[[menu.main]]
  identifier = "land-pack"
  name = "Land Pack"
  url = ""
  weight = 3
  [[menu.main]]
    identifier = "aurora-land-pack"
    parent = "land-pack"
    name = "Aurora"
    url = "/land-pack/aurora/"
    weight = 1
  [[menu.main]]
    identifier = "starfield-land-pack"
    parent = "land-pack"
    name = "Starfield"
    url = "/land-pack/starfield/"
    weight = 2
  [[menu.main]]
    identifier = "boreal-sky-land-pack"
    parent = "land-pack"
    name = "Boreal Sky"
    url = "/land-pack/boreal-sky/"
    weight = 3
  [[menu.main]]
    identifier = "clouds-land-pack"
    parent = "land-pack"
    name = "Clouds"
    url = "/land-pack/clouds/"
    weight = 4
  [[menu.main]]
    identifier = "colors-land-pack"
    parent = "land-pack"
    name = "Colors"
    url = "/land-pack/colors/"
    weight = 5
  [[menu.main]]
    identifier = "glitch-land-pack"
    parent = "land-pack"
    name = "Glitch"
    url = "/land-pack/glitch/"
    weight = 6
  [[menu.main]]
    identifier = "liquid-land-pack"
    parent = "land-pack"
    name = "Liquid"
    url = "/land-pack/liquid/"
    weight = 7
  [[menu.main]]
    identifier = "surface-land-pack"
    parent = "land-pack"
    name = "Surface"
    url = "/land-pack/surface/"
    weight = 8
  [[menu.main]]
    identifier = "hills-land-pack"
    parent = "land-pack"
    name = "Hills"
    url = "/land-pack/hills/"
    weight = 9
  [[menu.main]]
    identifier = "landscape-1-land-pack"
    parent = "land-pack"
    name = "Landscape 1"
    url = "/land-pack/landscape"
    weight = 10
  [[menu.main]]
    identifier = "landscape-2-land-pack"
    parent = "land-pack"
    name = "Landscape 2"
    url = "/land-pack/landscape-2/"
    weight = 11
  [[menu.main]]
    identifier = "quantum-land-pack"
    parent = "land-pack"
    name = "Quantum"
    url = "/land-pack/quantum/"
    weight = 12
  [[menu.main]]
    identifier = "star-wars-land-pack"
    parent = "land-pack"
    name = "Star Wars"
    url = "/land-pack/star-wars/"
    weight = 13
  [[menu.main]]
    identifier = "stars-lines-land-pack"
    parent = "land-pack"
    name = "Stars Lines"
    url = "/land-pack/stars-lines/"
    weight = 14
  [[menu.main]]
    identifier = "topology-land-pack"
    parent = "land-pack"
    name = "Topology"
    url = "/land-pack/topology/"
    weight = 15
  [[menu.main]]
    identifier = "water-droplet-land-pack"
    parent = "land-pack"
    name = "Water Droplet"
    url = "/land-pack/water-droplet/"
    weight = 16
  [[menu.main]]
    identifier = "html5-video-land-pack"
    parent = "land-pack"
    name = "HTML5 Video"
    url = "/land-pack/html5-video/"
    weight = 17
  [[menu.main]]
    identifier = "rain-video-land-pack"
    parent = "land-pack"
    name = "Rain Video"
    url = "/land-pack/rain-video/"
    weight = 18
  [[menu.main]]
    identifier = "winter-land-pack"
    parent = "land-pack"
    name = "Winter"
    url = "/land-pack/winter/"
    weight = 19
  [[menu.main]]
    identifier = "youtube-constellation.md"
    parent = "land-pack"
    name = "YouTube Constellation"
    url = "/land-pack/youtube-constellation/"
    weight = 20
[[menu.main]]
  identifier = "blog"
  name = "Blog"
  #url = "blog/"
  url = ""
  weight = 6


# Blog Settings
[params]
  defaultLogo = "Data from the Field"
  defaultKeywords = ["geospatial data science", "machine learning", "gps", "movement pattern", "trajectory profiling", "GPS telemetry", "offroad", "remote", "connectivity", "starlink", "onboard sensors", "vehicle technology"]
  defaultDescription = "Data from the Field - geospatial data science, machine learning engineering from the field, usually off-road"
  dateFormat = "January 2, 2006"
  authorName = "jcachat"
  disqusComments = "mountain-hugo" #YOUR DISQUS COMMENTS SHORTNAME
  googleAnalytics = "G-PHRTNHNRLN" #YOUR GOOGLE ANALYTICS CODE

# Preloader Settings
[params.preloader]
  logo = "/images/spinner.gif"

# Blog Sidebar
[params.sidebar]
  enable = 1 #SIDEBAR SHOW: [ 1 - yes, 0 - no ]
  search = 1 #SIDEBAR SEARCH WIDGET: [ 1 - yes, 0 - no ]
  latestPosts = 1 #SIDEBAR LATEST POSTS WIDGET: [ 1 - yes, 0 - no ]
  categories = 1 #SIDEBAR CATEGORIES TAXONOMY WIDGET: [ 1 - yes, 0 - no ]
  tags = 1 #SIDEBAR TAG TAXONOMY WIDGET: [ 1 - yes, 0 - no ]

# Footer Settings
[params.footer]
  copyright = "Data from the Field © 2025. Design & Coded by <a href='https://jcachat.com' target='_blank'> Jonathan Cachat / CCV Research, LLC.</a>"

# Up Button Settings
[params.upBtn]
  icon = "fa-solid fa-chevron-up"
  url = "#top"

# Social Settings
[[params.social]]
  title = "YouTube"
  icon = "fa-brands fa-youtube"
  url = "https://www.youtube.com/@jcachat"
[[params.social]]
  title = "Twitter"
  icon = "fa-brands fa-x-twitter"
  url = "https://www.x.com/jcachat"
[[params.social]]
  title = "LinkedIn"
  icon = "fa-brands fa-linkedin"
  url = "https://linkedin.com/in/jcachat"
[[params.social]]
  title = "Instagram"
  icon = "fa-brands fa-instagram"
  url = "https://www.instagram.com/jcachat"


# Sitemap Settings
[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[outputs]
  home = ["HTML", "RSS", "JSON"]